const MY_CUSTOM_LETTER = `To my dearest <span style="color:#ffe4b5">Cara</span>,

    Happy 5th Monthsaryyy, my caraa, my loveyytootoottt... and holy shit.. five months in on having you in my life, and honestly baby, <b><span style="color:#ffd700">every| single| rule|</span></b> of my universe has completely changed. Bc ever since you came into my world, you've basically rewritten everything na i thought na alam ko about sa happiness na yan, and js turning those normal days|| to something thats to be looking foward everyday for... 

    thoughh speakinggggggg of completely changing the rules of the universe, Alam ko on how much you love *Death Note* and that solidddd 9/10 that we talked about, it js really got me thinking.. What if yk a notebook capable of altering reality and rewriting human fate actually dropped sa langit on my own hands... honestly i wouldnt care about changing the world or playing god at all|| kasi duhh alam naman natin kung ano talagang ginagawa ng notebook na yan, pero since your name is literally all over this website edi|i|i||| iniba ko nalang ung mga rules, that easy right😘 andd the exact second your name touched these pages, it basically js instantly turned into a Love Note na already| and instead of bringing harm, it 100% gurantees a lifetime of absolute peace, happiness, infinite laughs, and many other memories for us to share.. 

    and yeah speaking of the anime, L might be a genius at solving the very very hard mysteries, pero i am confident about this one thing|| bc he could never decipher the way my heart beats js for you.. you ARE literally| the only one who completely figured me out and unlocked exactly who i am. And baby, need ni ryuk ng apples, and compared to mine|| all i needed was you, your voice, your presence, and basically every part of you baby. Bc you ARE the ONLY name i ever want written in the book of my life, covering these every pages|| from now until the very merry fucking end.. <span style="color:#ffe4b5">Cara</span>, my baby, i am writing this to you kasi as always i will always want to create something thats COMPLETELY ours, and a quiet space where i could try, even if words will always fall short, to tell you js how much you damn mean to me. Nilagay ko 'to, and gusto ko na always in this specific corner of the internet to be a permanent sanctuary for the both of us||, a place you can always click on whenever you need a reminder of how deeply you are anchored in my very soul...

    first, i want to say thank you🥹. Thank you for staying by my side through absolutely everything, through every single up and down, and for being so deeply committed to us. Sobrang laking bagay sa akin nun baby seryoso||. It takes an incredibly strong, beautiful, and patient heart para mahalin ang isang katulad ko, and i promise never to take a single second of it for granted🥹🥹. Hawak-hawak mo lang yung kamay ko, mapa-chill man yung moment o mapuno ng gulo sa laro man o sa totoong buhay, hindi mo talaga ako binitawan. At yun ang pinakamagandang gift na natanggap ko sa buong buhay ko, no joke cara.. i know i can be a handful sometimes, and im sorry for being anxious at some things, and i really appreciate you reassuring me|| when i overthink badly. 

    the thought of causing you even a moment of stress or lungkot, grabe, pinalalambot talaga nun yung puso ko sa lungkot|| kasi you ARE the last person i ever want to hurt. Thank you for looking past my flaws, tinatanggap mo pa rin ako kahit ganito ako, and for creating a safe space kung saan feeling ko super safe ako mag-grow at matuto kasama ka. But please know that through every single second of these past five months, i have been so deeply, genuinely happy. Being loved by you is the greatest thing that has ever happened to me||. Yung pakiramdam na minamahal mo ako? Sobrang pure, to the point na nawawala lahat ng worries at overthinking ko. Doon ko talaga na-realize kung gaano ako ka-swerte na akin ka, as in LITERALLY| the luckiest guy in the universe.

    i want to be completely honest and vulnerable with you about something... Just yesterday, right before our monthsary, when we were both playing and we had that fight... it hurt so badly. My chest felt so incredibly heavy, love.. like it literally ached to the point where i could barely breathe. i was js so shocked bc you ARE the absolute last person i ever want to fight with or have a gap with||, especially today. When we were arguing and those mean things were said in the heat of anger, i couldn't help but cry. It wasn't js bc of the argument itself, <span style="color:#ffe4b5">Cara</span>.. 

    The real reason my heart broke| and the tears wouldnt stop|| was bc right at that exact moment, while we were playing, i was secretly working on this very website for you... While everything was a mess and we were fighting over the game, i had all these tabs open in the background—the code, the design layouts, and the letters i was writing for you. i was right here, crafting these pages and writing this letter, trying to build something beautiful|| to surprise you and make you smile. 

    it was js so devastating, bc while my tears were literally falling onto the keyboard, i was staring at my screen... completely stuck on this very code and website where i was typing out how much i love you, while at the exact same time, hearing how much we were hurting. It felt so incredibly bitter and overwhelming||. My chest felt so tight knowing that the one thing i was building to be our safe space was suddenly drowning in sadness. it's like our own universe was starting to collapse right then, and it broke me completely||. 

    i was crying over the fact that i was reading your name and pouring all my love into this site, but at the same time, my heart was breaking over what was happening to us. These two completely different worlds collided, and it felt so fucking bad. To be pouring my heart into celebrating us while we were actively hurting... it completely shattered me||. My only goal for today was js to make you happy and see you smile, so when it felt like i failed, i js completely lost all my strength|| and started panicking so hard..  

    But even in that heavy moment, it only made me realize|| how much i never want to lose you. Na-realize ko na isang mundo na wala ka, o isang buhay kung saan hahayaan lang natin na sira ang lahat... hindi ko talaga kayang tanggapin yun. i will never accept that reality||. It proved to me how deeply i care, and how much our bond matters to me. Alam ko naman na pinag-usapan natin nung isang araw yung side mo kapag galit ka, and i know you can get really harsh talaga pagdating sa ganun. Sabi ko naman sayo na kaya kong tiisin at tanggapin lahat ng yun, and i mean it||. 

    kaya kahit na umiyak ako, hindi ibig sabihin nun na mahina ako or na sumusuko na ako sa atin. Puso ko lang talaga yung nasasaktan sa moment na yun kasi mahal na mahal kita, pero hinding-hindi ako mapapagod na ipaglaban ka||. Arguments will happen, and we will face rough days, but the fact that you are still here, that we always find our way back, and that you stay committed to us through the storm|| means the entire world to me. Doon ko napatunayan na hindi fragile yung meron tayo; matibay 'to, deeply rooted, at kayang lagpasan kahit ano. Every time na nagkakaayos tayo at pinipili natin ang isa't isa pagkatapos ng gulo, lalo lang lumalalim at nadadagdagan yung pagmamahal ko sa'yo. You are my safe space, my anchor, and my home. Kahit gaano kagulo o ka-toxic ang mundo sa labas, basta pagdating sa'yo... all i'm seeing is my safe space, my home, and my world.

    If i could have one absolute wish for us, kind of like that movie Obsession where Bear wishes for Nikki to love him more than anyone else in the world, but without any of the craziness, js pure, wholesome devotion... my wish would be this||:

    i wish that as time goes on, your heart finds a love in me so deep, so safe, and so completely fulfilling|| that you never have to wonder what it feels like to be entirely cherished. Gusto ko yung love natin feels like a warm blanket tuwing malamig ang gabi, isang constant assurance na hawak mo ang puso ng isang tao na hinding-hindi ka bibiguin o sasaktan. i wish for me to be the person who makes you feel safer, happier, and more loved than anyone else ever could, and i wish for us to keep choosing each other, over and over again, growing closer with every single chapter we write. Sana sa future natin, punong-puno tayo ng mga milestones na babalikan natin habang naka-ngiti ng sobrang laki, knowing na nalagpasan natin lahat ng struggles ng magkahawak-kamay... i want to spend forever making sure yk|| that you are my absolute everything. Every single beat of my heart is a reminder na sa'yo lang ako, fully and completely, wala nang iba.

    but honestly... if we're really talking about being obsessed?| i am completely, insanely down for you, baby🥴🥴|| like, it's actually <span style="color:#9932cc"><b>terrifying how much you control my whole mood|</b></span> and how fast my world stops the second you're upset. i am <span style="color:#ff3333"><b>so dangerously locked in on you||</b></span> to the point that i don't care about anything else anymore. Call it crazy, but i love that <span style="color:#9932cc"><b>you own every single part of me||</b></span>. i want to know every single thing about you,| i want to hear your voice 24/7,| and i want to be <span style="color:#ff3333"><b>the only one who gets to hold you</b></span> when everything is a mess. It's like an <span style="color:#ff4500"><b>absolute addiction|</b></span> and i never ever want to get over it. You are my fixation, my constant thought,| and i would gladly let my <span style="color:#ff4500"><b>whole life revolve around you forever</b></span> because nobody else matters||.

    i know that movie is pretty wild and intense, but honestly.. if you just take away all the thriller and crazy stuff, the core feeling underneath is just so beautiful and romantic. Like, the vibe where you are someone's whole universe, their number one choice, and the only person they would protect against everyone else||. That's exactly how much i love you. i want to give you that exact same energy where i'm just completely locked in on you, but without any of the scary or heavy parts. We're just replacing it with the most gentle, sweet, and protective care i could ever give. 

    i just want to love you in the most wholesome way possible, the kind of love that always makes you feel better| and calms you down whenever you're tired or stressed about school or anything. i want you to feel so wrapped up in my love that you never ever have to guess how important you are, because you already know that inside and out, you are, and always will be, my number one priority||, no matter what...

    Thank you for these beautiful five months, <span style="color:#ffe4b5">Cara</span>. Thank you for your patience, your commitment, and your love||. You have honestly made me a better version of myself, at bawat araw na kasama kita, mas lalo kong napatutunayan kung gaano ka ka-mahalaga sa akin.

    Happy 5 Monthsary, my baby, my tootoot, my love, my cutiebaby, my <span style="color:#ffe4b5">Cara</span>... Forever and always, yours.

    XOXO - your carl
`;
